

trigger:
- master

pool:
  vmImage: 'ubuntu'

variables:
  solution: 'pusher.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'pusher.csproj'
