

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - src

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solution: 'pusher.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'